  const countryflags = {
  Algerian: "DZ",
  American: "US",
  Argentinian: "AR",
  Australian: "AU",
  British: "GB",
  Canadian: "CA",
  Chinese: "CN",
  Croatian: "HR",
  Dutch: "NL",
  Egyptian: "EG",
  Filipino: "PH",
  French: "FR",
  Greek: "GR",
  Indian: "IN",
  Irish: "IE",
  Italian: "IT",
  Jamaican: "JM",
  Japanese: "JP",
  Kenyan: "KE",
  Malaysian: "MY",
  Mexican: "MX",
  Moroccan: "MA",
  Norwegian: "NO",
  Polish: "PL",
  Portuguese: "PT",
  Russian: "RU",
  "Saudi Arabian": "SA",
  Slovakian: "SK",
  Spanish: "ES",
  Syrian: "SY",
  Thai: "TH",
  Tunisian: "TN",
  Turkish: "TR",
  Ukrainian: "UA",
  Uruguayan: "UY",
  Venezulan: "VE",
  Vietnamese: "VN"
};

export default countryflags;